/**
 * Command: epost-kit proposals
 *
 * List, show, approve, and reject skill evolution proposals.
 * Proposals live in docs/proposals/ and are generated by /plan --evolve.
 */

import { resolve } from 'node:path';
import pc from 'picocolors';
import Table from 'cli-table3';
import { logger } from '@/shared/logger.js';
import {
  loadProposals,
  filterByStatus,
  loadSignalsSummary,
  approveProposal,
  rejectProposal,
} from '@/domains/proposals/index.js';

interface ProposalsOptions {
  dir?: string;
  show?: string;
  approve?: string;
  reject?: string;
  reason?: string;
  stats?: boolean;
  all?: boolean;
}

const CONFIDENCE_COLOR = {
  high:   (s: string) => pc.red(s),
  medium: (s: string) => pc.yellow(s),
  low:    (s: string) => pc.dim(s),
};

const STATUS_COLOR = {
  pending:  (s: string) => pc.cyan(s),
  approved: (s: string) => pc.green(s),
  rejected: (s: string) => pc.dim(s),
};

export async function runProposals(opts: ProposalsOptions): Promise<void> {
  const cwd = resolve(opts.dir ?? process.cwd());

  // --- Stats mode ----------------------------------------------------------
  if (opts.stats) {
    const summary = loadSignalsSummary(cwd);
    if (!summary) {
      logger.error('No signals.json found. Run: node .claude/scripts/extract-signals.cjs');
      process.exit(1);
    }

    console.log('');
    console.log(pc.bold('Signal Summary'));
    console.log(`  Total: ${summary.summary.total}  New: ${summary.summary.new}  Proposed: ${summary.summary.proposed}  Dismissed: ${summary.summary.dismissed}`);
    console.log('');
    console.log(pc.bold('By type:'));
    for (const [type, count] of Object.entries(summary.summary.byType)) {
      if ((count as number) > 0) {
        console.log(`  ${type.padEnd(20)} ${count}`);
      }
    }
    console.log('');
    console.log(pc.bold('By skill:'));

    const skillTable = new Table({
      head: [pc.bold('Skill'), pc.bold('Total'), pc.bold('High'), pc.bold('Med'), pc.bold('Low')],
      style: { head: [], border: [] },
      colWidths: [28, 8, 8, 8, 8],
    });

    const skillEntries = Object.entries(summary.summary.bySkill as Record<string, any>)
      .sort(([, a], [, b]) => (b as any).total - (a as any).total);
    for (const [skill, counts] of skillEntries) {
      skillTable.push([
        skill,
        String((counts as any).total),
        (counts as any).high > 0 ? pc.red(String((counts as any).high)) : '0',
        (counts as any).medium > 0 ? pc.yellow(String((counts as any).medium)) : '0',
        String((counts as any).low),
      ]);
    }
    console.log(skillTable.toString());
    return;
  }

  // --- Show a single proposal -----------------------------------------------
  if (opts.show) {
    const proposals = loadProposals(cwd);
    const proposal = proposals.find(p => p.id === opts.show);
    if (!proposal) {
      logger.error(`Proposal not found: ${opts.show}`);
      process.exit(1);
    }

    console.log('');
    console.log(pc.bold(`Proposal: ${proposal.id}`));
    console.log(`  Skill:      ${pc.cyan(proposal.targetSkill)}`);
    console.log(`  File:       ${proposal.targetFile}`);
    console.log(`  Confidence: ${CONFIDENCE_COLOR[proposal.confidence]?.(proposal.confidence) ?? proposal.confidence}`);
    console.log(`  Status:     ${STATUS_COLOR[proposal.status]?.(proposal.status) ?? proposal.status}`);
    console.log(`  Created:    ${proposal.created}`);
    if (proposal.rejectedReason) {
      console.log(`  Rejected:   ${proposal.rejectedReason}`);
    }
    console.log('');
    console.log(proposal.body);
    return;
  }

  // --- Approve a proposal ---------------------------------------------------
  if (opts.approve) {
    const proposals = loadProposals(cwd);
    const proposal = proposals.find(p => p.id === opts.approve);
    if (!proposal) {
      logger.error(`Proposal not found: ${opts.approve}`);
      process.exit(1);
    }

    if (proposal.status !== 'pending') {
      logger.error(`Proposal ${opts.approve} is already ${proposal.status}. Cannot approve.`);
      process.exit(1);
    }

    const result = approveProposal(proposal, cwd);
    if (result.ok) {
      console.log(pc.green(`✓ ${result.message}`));
    } else {
      logger.error(result.message);
      process.exit(1);
    }
    return;
  }

  // --- Reject a proposal ----------------------------------------------------
  if (opts.reject) {
    const proposals = loadProposals(cwd);
    const proposal = proposals.find(p => p.id === opts.reject);
    if (!proposal) {
      logger.error(`Proposal not found: ${opts.reject}`);
      process.exit(1);
    }

    if (proposal.status !== 'pending') {
      logger.error(`Proposal ${opts.reject} is already ${proposal.status}. Cannot reject.`);
      process.exit(1);
    }

    const result = rejectProposal(proposal, opts.reason);
    console.log(result.ok ? pc.dim(result.message) : pc.red(result.message));
    return;
  }

  // --- List proposals (default) ---------------------------------------------
  const allProposals = loadProposals(cwd);
  const filtered = opts.all
    ? allProposals
    : filterByStatus(allProposals, ['pending']);

  if (filtered.length === 0) {
    const hint = opts.all ? '' : ' Use --all to see approved/rejected proposals.';
    logger.info(`No pending proposals found.${hint}`);
    logger.info(`Generate proposals: /plan --evolve  or  node .claude/scripts/extract-signals.cjs`);
    return;
  }

  const table = new Table({
    head: [
      pc.bold('ID'),
      pc.bold('Skill'),
      pc.bold('Confidence'),
      pc.bold('Status'),
      pc.bold('Created'),
    ],
    style: { head: [], border: [] },
    colWidths: [30, 22, 12, 12, 12],
  });

  for (const p of filtered) {
    const confFn = CONFIDENCE_COLOR[p.confidence] ?? ((s: string) => s);
    const statusFn = STATUS_COLOR[p.status] ?? ((s: string) => s);
    table.push([
      pc.cyan(p.id),
      p.targetSkill,
      confFn(p.confidence),
      statusFn(p.status),
      p.created,
    ]);
  }

  console.log('');
  console.log(table.toString());
  console.log('');
  logger.info(`${filtered.length} proposal(s). Use ${pc.cyan('epost-kit proposals --show <id>')} to inspect, ${pc.cyan('--approve <id>')} to apply.`);
}
