/**
 * Command: epost-kit verify
 * Full pre-release/pre-init audit pipeline.
 * Runs integrity check + lint + health checks + generates mermaid dependency graph.
 */

import { writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { existsSync, mkdirSync } from "node:fs";
import pc from "picocolors";
import { dirExists, fileExists } from "@/shared/file-system.js";
import { loadAllManifests } from "@/domains/packages/package-resolver.js";
import {
  buildRefRegistry,
  validateReferences,
} from "@/domains/validation/ref-validator.js";
import { runSkillHealthChecks } from "@/domains/health-checks/skill-health-checks.js";
import { checkInstalledIntegrity } from "@/domains/health-checks/integrity-checker.js";
import { logger } from "@/shared/logger.js";
import type { IntegritySummary } from "@/domains/health-checks/integrity-checker.js";

interface VerifyOptions {
  verbose?: boolean;
  yes?: boolean;
  strict?: boolean;
  dir?: string;
  json?: boolean;
  fix?: boolean;
}

interface VerifyReport {
  timestamp: string;
  integrity: {
    total: number;
    ok: number;
    modified: string[];
    missing: string[];
    extra: string[];
    metadataPresent: boolean;
  };
  refs: { errors: unknown[]; count: number };
  health: {
    issues: unknown[];
    stats: {
      skillCount: number;
      connectionCount: { extends: number; requires: number; conflicts: number; enhances: number };
      completeness: { withDescription: number; withKeywords: number; withPlatforms: number };
    };
  };
  graph: { path: string; skillCount: number; connectionCount: number };
  summary: { errors: number; warnings: number; infos: number; pass: boolean };
}

async function findPackagesDir(cwd: string): Promise<string | null> {
  const paths = [join(cwd, "packages"), join(cwd, "..", "packages")];
  for (const p of paths) {
    const resolved = resolve(p);
    if (
      (await dirExists(resolved)) &&
      (await fileExists(join(resolved, "core", "package.yaml")))
    ) {
      return resolved;
    }
  }
  return null;
}

// ─── Mermaid Graph Generator ───

function generateMermaidGraph(healthStats: {
  skillCount: number;
  connectionCount: { extends: number; requires: number; conflicts: number; enhances: number };
}, allConnections: Map<string, { extends: string[]; requires: string[]; conflicts: string[]; enhances: string[] }>): string {
  const lines: string[] = [
    "# Skill Dependency Graph",
    "",
    "> Auto-generated by `epost-kit verify`. Do not edit manually.",
    "",
    "```mermaid",
    "graph TD",
  ];

  // Add nodes and edges from connections
  for (const [skill, conn] of allConnections) {
    const safeId = skill.replace(/-/g, "_");

    for (const parent of conn.extends) {
      const parentId = parent.replace(/-/g, "_");
      lines.push(`  ${parentId}[${parent}] --> ${safeId}[${skill}]`);
    }

    for (const dep of conn.requires) {
      const depId = dep.replace(/-/g, "_");
      lines.push(`  ${depId}[${dep}] -.->|requires| ${safeId}[${skill}]`);
    }

    for (const target of conn.enhances) {
      const targetId = target.replace(/-/g, "_");
      lines.push(`  ${safeId}[${skill}] ~~~|enhances| ${targetId}[${target}]`);
    }

    for (const target of conn.conflicts) {
      const targetId = target.replace(/-/g, "_");
      lines.push(`  ${safeId}[${skill}] x--x|conflicts| ${targetId}[${target}]`);
    }
  }

  lines.push("```");
  lines.push("");

  // Stats summary
  const cc = healthStats.connectionCount;
  lines.push("## Stats");
  lines.push("");
  lines.push(`- **Skills**: ${healthStats.skillCount}`);
  lines.push(`- **Extends**: ${cc.extends}`);
  lines.push(`- **Requires**: ${cc.requires}`);
  lines.push(`- **Conflicts**: ${cc.conflicts}`);
  lines.push(`- **Enhances**: ${cc.enhances}`);
  lines.push("");

  return lines.join("\n");
}

// ─── Connection Extractor (reads from packages/) ───

async function extractAllConnections(
  packagesDir: string,
): Promise<Map<string, { extends: string[]; requires: string[]; conflicts: string[]; enhances: string[] }>> {
  const { readFile, readdir } = await import("node:fs/promises");
  const connections = new Map<string, { extends: string[]; requires: string[]; conflicts: string[]; enhances: string[] }>();

  async function findSkillFiles(dir: string): Promise<string[]> {
    const results: string[] = [];
    try {
      const entries = await readdir(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = join(dir, entry.name);
        if (entry.isDirectory()) results.push(...(await findSkillFiles(fullPath)));
        else if (entry.name === "SKILL.md") results.push(fullPath);
      }
    } catch { /* skip */ }
    return results;
  }

  // Reuse the frontmatter parser approach from skill-health-checks
  function parseFm(content: string): { name?: string; extends?: string[]; requires?: string[]; conflicts?: string[]; enhances?: string[] } {
    const match = content.match(/^---\s*\n([\s\S]*?)\n---/);
    if (!match) return {};

    const metadata: Record<string, string | string[]> = {};
    let currentKey: string | null = null;

    for (const line of match[1].split("\n")) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      if (trimmed.startsWith("-") && currentKey) {
        if (!Array.isArray(metadata[currentKey])) metadata[currentKey] = [];
        (metadata[currentKey] as string[]).push(trimmed.substring(1).trim());
        continue;
      }
      const ci = trimmed.indexOf(":");
      if (ci === -1) continue;
      const key = trimmed.substring(0, ci).trim();
      let value = trimmed.substring(ci + 1).trim();
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'")))
        value = value.substring(1, value.length - 1);
      if (value.startsWith("[") && value.endsWith("]")) {
        metadata[key] = value.substring(1, value.length - 1).split(",").map(i => i.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
      } else if (value) {
        metadata[key] = value;
      } else {
        currentKey = key;
      }
    }

    const asArr = (v: string | string[] | undefined): string[] => Array.isArray(v) ? v : [];
    return {
      name: typeof metadata.name === "string" ? metadata.name : undefined,
      extends: asArr(metadata.extends),
      requires: asArr(metadata.requires),
      conflicts: asArr(metadata.conflicts),
      enhances: asArr(metadata.enhances),
    };
  }

  const files = await findSkillFiles(packagesDir);
  for (const f of files) {
    try {
      const content = await readFile(f, "utf-8");
      const fm = parseFm(content);
      if (!fm.name) continue;
      const hasAny = (fm.extends?.length ?? 0) + (fm.requires?.length ?? 0) + (fm.conflicts?.length ?? 0) + (fm.enhances?.length ?? 0) > 0;
      if (hasAny) {
        connections.set(fm.name, {
          extends: fm.extends ?? [],
          requires: fm.requires ?? [],
          conflicts: fm.conflicts ?? [],
          enhances: fm.enhances ?? [],
        });
      }
    } catch { /* skip */ }
  }

  return connections;
}

// ─── Display Helpers ───

function displayIntegrity(integrity: IntegritySummary): void {
  if (!integrity.metadataPresent) {
    console.log(`  Integrity:    ${pc.yellow("no metadata — skipped")}`);
    return;
  }

  const hasIssues = integrity.modified.length > 0 || integrity.missing.length > 0;
  const statusStr = hasIssues
    ? pc.yellow(`${integrity.ok}/${integrity.total} ok, ${integrity.modified.length} modified, ${integrity.missing.length} missing`)
    : pc.green(`${integrity.ok}/${integrity.total} ok`);

  console.log(`  Integrity:    ${statusStr}`);

  if (integrity.extra.length > 0) {
    console.log(pc.dim(`  Extra files:  ${integrity.extra.length} untracked`));
  }
}

// ─── Main ───

export async function runVerify(opts: VerifyOptions): Promise<void> {
  const cwd = opts.dir ? resolve(opts.dir) : process.cwd();
  const claudeDir = join(cwd, ".claude");

  if (!(await dirExists(claudeDir))) {
    logger.error("No .claude/ directory found. Run epost-kit init first.");
    process.exit(1);
  }

  const packagesDir = await findPackagesDir(cwd);
  if (!packagesDir) {
    logger.error("Cannot find packages/ directory.");
    process.exit(1);
  }

  if (!opts.json) {
    console.log(pc.bold("\nepost-kit verify\n"));
  }

  // Run all checks in parallel
  const [refErrors, healthResult, allConnections, integrity] = await Promise.all([
    validateReferences(claudeDir, buildRefRegistry(await loadAllManifests(packagesDir))),
    runSkillHealthChecks(packagesDir, claudeDir, await loadAllManifests(packagesDir)),
    extractAllConnections(packagesDir),
    checkInstalledIntegrity(cwd),
  ]);

  const { issues, stats } = healthResult;

  const errors = issues.filter((i) => i.severity === "error");
  const warnings = issues.filter((i) => i.severity === "warn");
  const infos = issues.filter((i) => i.severity === "info");

  // Count integrity issues as warnings (modified) or errors (missing)
  const integrityErrors = integrity.missing.length;
  const integrityWarnings = integrity.modified.length;

  const totalErrors = refErrors.length + errors.length + integrityErrors;
  const totalWarnings = warnings.length + integrityWarnings;

  // ── Generate mermaid graph ──
  const docsDir = join(cwd, "docs");
  if (!existsSync(docsDir)) mkdirSync(docsDir, { recursive: true });

  const graphContent = generateMermaidGraph(stats, allConnections);
  const graphPath = join(docsDir, "skill-dependency-graph.md");
  await writeFile(graphPath, graphContent, "utf-8");

  // ── Determine exit code ──
  // 0=pass, 1=errors, 2=warnings-only (matches doctor convention)
  const hasErrors = totalErrors > 0;
  const hasWarnings = totalWarnings > 0;
  const strictFail = opts.strict && hasWarnings;

  let exitCode = 0;
  if (hasErrors || strictFail) {
    exitCode = 1;
  } else if (hasWarnings) {
    exitCode = 2;
  }

  // ── JSON output ──
  if (opts.json) {
    const cc = stats.connectionCount;
    const totalConnections = cc.extends + cc.requires + cc.conflicts + cc.enhances;

    const report: VerifyReport = {
      timestamp: new Date().toISOString(),
      integrity: {
        total: integrity.total,
        ok: integrity.ok,
        modified: integrity.modified,
        missing: integrity.missing,
        extra: integrity.extra,
        metadataPresent: integrity.metadataPresent,
      },
      refs: {
        errors: refErrors,
        count: refErrors.length,
      },
      health: {
        issues,
        stats,
      },
      graph: {
        path: graphPath,
        skillCount: stats.skillCount,
        connectionCount: totalConnections,
      },
      summary: {
        errors: totalErrors,
        warnings: totalWarnings,
        infos: infos.length,
        pass: exitCode === 0,
      },
    };

    console.log(JSON.stringify(report, null, 2));
    process.exit(exitCode);
    return;
  }

  // ── Human-readable report ──
  displayIntegrity(integrity);
  console.log(`  Refs:         ${refErrors.length === 0 ? pc.green("OK") : pc.red(`${refErrors.length} broken`)}`);
  console.log(`  Skills:       ${stats.skillCount} found`);
  console.log(`  Connections:  ${stats.connectionCount.extends}e ${stats.connectionCount.requires}r ${stats.connectionCount.conflicts}c ${stats.connectionCount.enhances}h`);
  console.log(`  Completeness: ${stats.completeness.withDescription}/${stats.skillCount} desc, ${stats.completeness.withKeywords}/${stats.skillCount} kw, ${stats.completeness.withPlatforms}/${stats.skillCount} plat`);
  console.log();

  if (totalErrors > 0) {
    console.log(pc.red(`  ${totalErrors} error(s) — blocking`));
    for (const e of errors) {
      console.log(`    ${pc.red("✗")} [${e.rule}] ${e.skill}: ${e.message}`);
    }
    for (const f of integrity.missing) {
      console.log(`    ${pc.red("✗")} [integrity] missing: ${f}`);
    }
  }

  if (totalWarnings > 0) {
    console.log(pc.yellow(`  ${totalWarnings} warning(s)`));
    if (opts.verbose) {
      for (const f of integrity.modified) {
        console.log(`    ${pc.yellow("~")} [integrity] modified: ${f}`);
      }
    }
  }

  if (infos.length > 0) {
    console.log(pc.dim(`  ${infos.length} info`));
  }

  if (!integrity.metadataPresent) {
    console.log(pc.yellow("  Warning: .epost-metadata.json not found — integrity check skipped"));
  }

  console.log(pc.dim(`\n  Graph: ${graphPath}`));

  // ── Exit ──
  if (hasErrors || strictFail) {
    if (strictFail && !hasErrors) {
      console.log(pc.yellow("\n  FAIL — strict mode: warnings treated as errors\n"));
    } else {
      console.log(pc.red("\n  FAIL — errors must be fixed before release/init\n"));
    }
    process.exit(1);
  } else if (hasWarnings) {
    console.log(pc.green("\n  PASS") + pc.yellow(" (with warnings)\n"));
    process.exit(2);
  } else {
    console.log(pc.green("\n  PASS\n"));
    process.exit(0);
  }
}
